// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsE-nyxJabVqdorxLQa-BHhJHQeyNi2dI',
    appId: '1:213628458384:android:5e3e0252706a2bb4a90f15',
    messagingSenderId: '213628458384',
    projectId: 'twitter-clon-e069c',
    storageBucket: 'twitter-clon-e069c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSFHvyaVv3J6Y5iUaLLn2VT-758tCt20g',
    appId: '1:213628458384:ios:6be1b4456e2cafa1a90f15',
    messagingSenderId: '213628458384',
    projectId: 'twitter-clon-e069c',
    storageBucket: 'twitter-clon-e069c.firebasestorage.app',
    iosBundleId: 'com.example.aplicaccion2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbCJA8fhOYNl960rM17JtemY67np-L6k0',
    appId: '1:213628458384:web:f6d4263312fe39a8a90f15',
    messagingSenderId: '213628458384',
    projectId: 'twitter-clon-e069c',
    authDomain: 'twitter-clon-e069c.firebaseapp.com',
    storageBucket: 'twitter-clon-e069c.firebasestorage.app',
    measurementId: 'G-13N35Q9GMV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSFHvyaVv3J6Y5iUaLLn2VT-758tCt20g',
    appId: '1:213628458384:ios:6be1b4456e2cafa1a90f15',
    messagingSenderId: '213628458384',
    projectId: 'twitter-clon-e069c',
    storageBucket: 'twitter-clon-e069c.firebasestorage.app',
    iosBundleId: 'com.example.aplicaccion2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbCJA8fhOYNl960rM17JtemY67np-L6k0',
    appId: '1:213628458384:web:caca2e2d162b91e5a90f15',
    messagingSenderId: '213628458384',
    projectId: 'twitter-clon-e069c',
    authDomain: 'twitter-clon-e069c.firebaseapp.com',
    storageBucket: 'twitter-clon-e069c.firebasestorage.app',
    measurementId: 'G-5GVN83Q8JB',
  );

}